### ISSUE TITLE
check_disks_snmp.pl fails to run with 'Global symbol "%result"' message

### ISSUE THREAD

**Issue by DrydenK** [nullDowntimeLtd/nagios_plugins#4]
Hi,

I've downloaded the check_disks_snmp.pl plugin and tried to run it, but got the following error:
root@server:/usr/local/nagios/libexec# ./check_disks_snmp.pl
Global symbol "%result" requires explicit package name at ./check_disks_snmp.pl line 241.
Global symbol "%result" requires explicit package name at ./check_disks_snmp.pl line 241.
Global symbol "%result" requires explicit package name at ./check_disks_snmp.pl line 255.
Global symbol "%result" requires explicit package name at ./check_disks_snmp.pl line 256.
Execution of ./check_disks_snmp.pl aborted due to compilation errors.

The server is a Debian 7 machine with Nagios 4.0.8 running. Net::SNMP is installed and working fine, as I have other plugins running that use SNMP (check_snmp_load.pl, check_snmp_int.pl and others). Any idea of what the problem can be?

Tks,

Roberto

**Comment by nulldowntime** [comment]
Possibly bad referencing, could you check if the below works for you?

https://github.com/nullDowntimeLtd/nagios_plugins/blob/fix/issue/4/check_disks_snmp.pl

If not I'll have to set up a test bed, it could take a while.

**Comment by DrydenK** [comment]
That error was indeed corrected, but now I'm getting the following error:
root@server:/usr/local/nagios/libexec# ./check_disks_snmp.pl -H <target> -p <community> -w 80 -c 90
Use of uninitialized value in concatenation (.) or string at ./check_disks_snmp.pl line 273.

Adding or removing a few of the parameters (-w, -W, etc) did not seem the alter the error.

Roberto

**Comment by nulldowntime** [comment]
I've updated the file in the same branch with what looks like a fix. perfdata was not set in disk_h, but referenced in line 273. Check if it works for you now.

**Comment by DrydenK** [comment]
Cool.

It works fine now. Also checked with very low values in -w and -W to see if it reported correct values and it reported the values correctly.

Tks.

Roberto

**Comment by nulldowntime** [comment]
Great. I'll merge it now then.
